import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

function getTomorrowDateString() {
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(0, 0, 0, 0);

  const year = tomorrow.getFullYear();
  const month = String(tomorrow.getMonth() + 1).padStart(2, "0");
  const day = String(tomorrow.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const pilotParam = searchParams.get("pilot");

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  const resend = new Resend(process.env.RESEND_API_KEY!);

  const date = getTomorrowDateString();

  let query = supabase
    .from("calendar_events")
    .select("google_email, origin, destination, start_time")
    .gte("start_time", `${date}T00:00:00`)
    .lte("start_time", `${date}T23:59:59`);

  if (pilotParam) {
    query = query.eq("google_email", pilotParam);
  }

  const { data: flights, error: flightError } = await query;

  if (flightError) {
    console.error("Flight query failed:", flightError);
    return NextResponse.json({ error: "Flight query failed" });
  }

  if (!flights || flights.length === 0) {
    return NextResponse.json({ message: "No flights tomorrow" });
  }

  const pilots: Record<string, any> = {};

  for (const flight of flights) {
    const email = flight.google_email;

    if (!pilots[email]) {
      pilots[email] = {
        flights: [],
        airports: new Set<string>(),
      };
    }

    pilots[email].flights.push(flight);

    if (flight.origin) pilots[email].airports.add(flight.origin);
    if (flight.destination) pilots[email].airports.add(flight.destination);
  }

  const results = [];

  for (const email in pilots) {
    const { data: existing } = await supabase
      .from("briefing_sent")
      .select("id")
      .eq("pilot_email", email)
      .eq("briefing_date", date)
      .maybeSingle();

    if (existing) {
      results.push({
        pilot: email,
        skipped: "already_sent",
      });
      continue;
    }

    const airportList = Array.from(pilots[email].airports);

    const { data: notams, error: notamError } = await supabase
      .from("airport_notams")
      .select("airport, summary, severity")
      .eq("briefing_date", date)
      .in("airport", airportList);

    if (notamError) {
      console.error("NOTAM query failed:", notamError);
    }

    const flightsSorted = pilots[email].flights.sort(
      (a: any, b: any) =>
        new Date(a.start_time).getTime() - new Date(b.start_time).getTime()
    );

    let emailBody = `
      <h2>NOTAM Briefing – Tomorrow</h2>
      <hr/>
      <h3>Flights</h3>
    `;

    flightsSorted.forEach((f: any) => {
      const time = new Date(f.start_time).toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
      });

      emailBody += `<p>${f.origin} → ${f.destination} ${time}</p>`;
    });

    emailBody += `
      <hr/>
      <h3>Airport NOTAMs</h3>
    `;

    airportList.forEach((airport: any) => {
      const airportNotam = notams?.find((n) => n.airport === airport);

      emailBody += `
        <p>
          <strong>${airport}</strong><br/>
          ${airportNotam?.severity || "GREEN"} —
          ${airportNotam?.summary || "No significant NOTAMs."}
        </p>
      `;
    });

    emailBody += `
      <hr/>
      <p style="font-size:12px;color:gray">
      Generated by NOTAM.pro
      </p>
    `;

    const { error: emailError } = await resend.emails.send({
      from: "NOTAM.pro <onboarding@resend.dev>",
      to: email,
      subject: "Tomorrow's NOTAM Briefing",
      html: emailBody,
    });

    if (emailError) {
      console.error("Email send error:", emailError);
    }

    if (!emailError) {
      await supabase.from("briefing_sent").insert({
        pilot_email: email,
        briefing_date: date,
      });
    }

    results.push({
      pilot: email,
      airports: airportList,
      emailSent: !emailError,
    });
  }

  return NextResponse.json({
    pilotsProcessed: Object.keys(pilots).length,
    results,
  });
}