import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

export async function GET() {

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  const resend = new Resend(process.env.RESEND_API_KEY!);

  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  const date = tomorrow.toISOString().split("T")[0];

  // fetch tomorrow flights
  const { data: flights } = await supabase
    .from("calendar_events")
    .select("google_email, origin, destination, start_time")
    .gte("start_time", `${date}T00:00:00`)
    .lte("start_time", `${date}T23:59:59`);

  if (!flights || flights.length === 0) {
    return NextResponse.json({ message: "No flights tomorrow" });
  }

  // group flights by pilot
  const pilots: any = {};

  for (const flight of flights) {

    const email = flight.google_email;

    if (!pilots[email]) {
      pilots[email] = {
        flights: [],
        airports: new Set()
      };
    }

    pilots[email].flights.push(flight);

    if (flight.origin) pilots[email].airports.add(flight.origin);
    if (flight.destination) pilots[email].airports.add(flight.destination);
  }

  const results = [];

  for (const email in pilots) {

    const airportList = Array.from(pilots[email].airports);

    const { data: notams } = await supabase
      .from("airport_notams")
      .select("airport, summary, severity")
      .eq("briefing_date", date)
      .in("airport", airportList);

    // sort flights chronologically
    const flightsSorted = pilots[email].flights.sort(
      (a: any, b: any) =>
        new Date(a.start_time).getTime() - new Date(b.start_time).getTime()
    );

    let emailBody = `
      <h2>NOTAM Briefing – Tomorrow</h2>
      <hr/>
      <h3>Flights</h3>
    `;

    flightsSorted.forEach((f: any) => {

      const time = new Date(f.start_time).toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit"
      });

      emailBody += `<p>${f.origin} → ${f.destination} ${time}</p>`;
    });

    emailBody += `
      <hr/>
      <h3>Airport NOTAMs</h3>
    `;

    airportList.forEach((airport: any) => {

      const airportNotam = notams?.find(n => n.airport === airport);

      emailBody += `
        <p>
          <strong>${airport}</strong><br/>
          ${airportNotam?.severity || "GREEN"} —
          ${airportNotam?.summary || "No significant NOTAMs."}
        </p>
      `;
    });

    emailBody += `
      <hr/>
      <p style="font-size:12px;color:gray">
      Generated by NOTAM.pro
      </p>
    `;

    const { error } = await resend.emails.send({
      from: "NOTAM.pro <onboarding@resend.dev>",
      to: email,
      subject: "Tomorrow's NOTAM Briefing",
      html: emailBody,
    });

    results.push({
      pilot: email,
      airports: airportList,
      emailSent: !error
    });
  }

  return NextResponse.json({
    pilotsProcessed: Object.keys(pilots).length,
    results
  });

}